source 'https://github.com/zhengya123/ZYModule.git'

platform :ios, '8.0'

target 'ZYUpVersion_Example' do
  pod 'ZYUpVersion', :path => '../'
  pod 'ZYCategoryKit','~>0.1.4'
  target 'ZYUpVersion_Tests' do
    inherit! :search_paths

    
  end
end
